config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses
  end
  resources :doses, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true

  # validations
end

  # cocktail.ingredients

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }#referes to column,only one, so singular ex: does.cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
    @doses = @cocktail.ingredients
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def create#post
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created!'
    else
      render :new
    end
  end

  def update#patch and put
    if @cocktail.update(cocktail_params)
      redirect_to @cocktail, notice: 'Cocktail was successfully updated!'
    else
      render :edit
    end
  end

  def destroy #delete
    @cocktail.destroy
    redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.'
  end

  private


  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end


  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.thefix.com/sites/default/files/styles/3col_222x186/public/socialdrinking.jpg);">
  <div class="container">
    <h1>Welcome to the simple whiskey bar <strong>GET SIMPLY BUZZED</strong> with <strong>GREAT PEOPLE</strong>!</h1>
    <p>come create your simple whiskey cocktails</p>

  </div>
</div>




<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://thequasifylife.com/wp-content/uploads/2018/10/4eab04a161722c6294e868c8bbecec97.jpg);">
  <div class="container">
    <h1>Create a whiskey cocktail!</h1>
  </div>
</div>
<div class="container pt-5">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6">
        <%= link_to cocktail_path(cocktail.id) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
            <%= cocktail.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>Give your cocktail a name~<h1>
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Cocktail Name:</strong>
  <%= @cocktail.name %>
</p>
<p>
<h2>Doses</h2>
<ul>
    <% @cocktail.doses.each do |dose| %>
      <li><%= dose.description %></li>
    <% end %>
</ul>
<h4>Ingredients</h4>
<ul>
  <% @cocktail.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %>
    <% ingredient.doses.each do |dose|%>
      <%= dose.description %>
      <p><%= link_to "delete", dose_path(dose), method: :delete  %>
     <% end %></li>
<% end %>
</ul>



|<%= link_to "Add dose" , new_cocktail_dose_path(@cocktail)  %>|
<%= link_to "Add a cocktail" , new_cocktail_path(@cocktail)  %>
| <%= link_to 'Edit Cocktail', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Delete Cocktail', cocktail_path(@cocktail), method: :delete  %> |
<%= link_to 'Home', cocktails_path %>

app/views/doses/new.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>